# Generated by Django 3.2.16 on 2023-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_image_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='place_id',
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ManyToManyField(blank=True, related_name='images', to='places.Place', verbose_name='Место'),
        ),
    ]
