# Generated by Django 4.1.6 on 2023-02-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_image_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
