# Generated by Django 4.1.6 on 2023-02-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_remove_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
    ]
