# Generated by Django 4.1.6 on 2023-02-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_image_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
